 import Image from 'next/image';
import { Inter } from 'next/font/google';
import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, } from "react-icons/ai";
import image1 from "../../public/milad-fakurian-Bdg_kKtAKig-unsplash.jpg";
import image2 from "../../public/simon-lee-O3oIMSvv6O8-unsplash.jpg";
import image3 from "../../public/sebastian-svenson-LpbyDENbQQg-unsplash.jpg"
import image4 from "../../public/warren-hansen-uCMNeSNS54U-unsplash.jpg";
import image5 from "../../public/roman-skrypnyk-DEga33BYvmA-unsplash.jpg";
import image6 from "../../public/guerrillabuzz-ZR2dtQ0hUhA-unsplash.jpg";
import code from "../../public/hans-eiskonen-8Pm_A-OHJGg-unsplash.jpg"
import Icon from "../../public/rubaitul-azad-TVnvFrZG7Vg-unsplash.jpg";
import { useState } from 'react';



const inter = Inter({ subsets: ['latin'] });


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Oladepo David</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
    

    <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
      <section className="min-h-screen">
        <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-xl font-burtons">developedbyete</h1>
         <ul className="flex items-center">
           <li>
             <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}   className="cursor-pointer text-2xl" />
           </li>
           <li><a className="bg-cyan-500 text-white px-4 py-2 rounded-md ml-8 bg-gradient-to-r from-cyan-500 to-teal-500" href="#">Resume</a></li> 
          </ul>  
        </nav>
        <div className="text-center p-10">
          <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Oladepo David</h2>
          <h3 className="text-2xl py-2 md:text-3xl">Fullstack Developer.</h3>
          <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto">Freelancer providing services for programming needs. Join me down below and let's get crazy</p>  
        </div>
        <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
          <AiFillTwitterCircle />
          <AiFillLinkedin />
          <AiFillYoutube />  
        </div>  
        <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
         <Image src={image1} layout="fill" objectFit="cover" /> 
        </div>
      </section>      

       <section>
         <div className="py-10">
           <h3 className="text-3xl py-1 ">Services I offer</h3>
           <p className="text-md py-2 leading-8 text-gray-80">
             Since the  beginning of my journey as a freelance developer, i've done remote work for
             <span className="text-teal-500">agencies </span> and collaborated with talented people to create digital products for 
             business and customer use.
           </p>
           <p className="text-md py-2 leading-8 text-gray-800">
             I offer from a wide range of services, including both frontend and backend. 
           </p>
         </div>

         <div>
         <div className="lg:flex gap-10">
          <div className="shadow-lg p-10 rounded-xl my-10">
            <Image src={code} width={100} height={120} className="rounded-lg" />
           <h3 className="text-lg font-medium pt-8 pb-2">
             Beautiful websites
             </h3> 
             <p className="py-2">
               Creating powerful and elegant websites for your needs,
               following latest standards and using latest technologies. 
             </p>
             <h4 className="py-4 text-teal-600">Tools I use</h4>
             <p className="text-gray-800 py-1">React</p>
             <p className="text-gray-800 py-1">Nextjs</p>
             <p className="text-gray-800 py-1">Tailwind</p>
             <p className="text-gray-800 py-1">Sass</p>
          </div>
      
           
          <div className="shadow-lg p-10 rounded-xl my-10">
            <Image src={Icon} width={150} height={150} className="rounded-lg"/>
           <h3 className="text-lg font-medium pt-8 pb-2">
             Beautiful websites
             </h3> 
             <p className="py-2">
               Creating powerful and elegant websites for your needs,
               following latest standards and using latest technologies.
             </p>
             <h4 className="py-4 text-teal-600">Tools I use</h4>
             <p className="text-gray-800 py-1">React</p>
             <p className="text-gray-800 py-1">Nextjs</p>
             <p className="text-gray-800 py-1">Tailwind</p>
             <p className="text-gray-800 py-1">Sass</p>
          </div> 

    <div className="shadow-lg p-10 rounded-xl my-10">
            <Image src={Icon} width={160} height={160} className="rounded-lg" />
           <h3 className="text-lg font-medium pt-8 pb-2">
             Beautiful websites
             </h3> 
             <p className="py-2">
               Creating powerful and elegant websites for your needs,
               following latest standards and using latest technologies.
             </p>
             <h4 className="py-4 text-teal-600">Tools I use</h4>
             <p className="text-gray-800 py-1">React</p>
             <p className="text-gray-800 py-1">Nextjs</p>
             <p className="text-gray-800 py-1">Tailwind</p>
             <p className="text-gray-800 py-1">Sass</p>
          </div> 
     
          </div>
          </div>
       </section>
       <section>
         <div>
         <h3 className="text-3xl py-1">My Portfolio</h3>
           <p>These are the projects that wi have done </p>

         </div>
         <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
           <div className="basis-1/3 flex-1">
             <Image src={image2} className="rounded-lg object-cover"  width={'100%'} height={'100%'} layout="responsive" />
           </div>
           <div className="basis-1/3 flex-1">
             <Image src={image3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
           </div>
           <div className="basis-1/3 flex-1">
             <Image src={image4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
           </div>
           <div className="basis-1/3 flex-1">
             <Image src={image5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" />
           </div>
           <div className="basis-1/3 flex-1">
             <Image src={image6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
           </div>
         </div>
       </section>
    </main>
    </div>
  );
}
